<?php

namespace App\Imports;

use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Maatwebsite\Excel\Concerns\SkipsOnFailure;
use Maatwebsite\Excel\Concerns\SkipsFailures;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;

class UsersImport implements ToModel, WithHeadingRow, WithValidation, SkipsOnFailure
{
    use SkipsFailures;

    /**
     * Normalize heading names so CSVs generated by Excel (BOM),
     * or headings with extra spaces/different casing still work.
     */
    public function headingRowFormatter(): callable
    {
        return function ($heading) {
            $heading = (string) $heading;
            // Remove UTF-8 BOM if present
            $heading = preg_replace('/^\xEF\xBB\xBF/', '', $heading);
            // Trim and normalize
            $heading = strtolower(trim($heading));
            // Collapse spaces to underscores (e.g. "Full Name" -> "full_name")
            $heading = preg_replace('/\s+/', '_', $heading);

            return $heading;
        };
    }

    public function model(array $row)
    {
        $email = strtolower(trim((string) ($row['email'] ?? '')));
        $name = trim((string) ($row['name'] ?? ''));
        $role = trim((string) ($row['role'] ?? ''));
        $password = (string) ($row['password'] ?? '');

        if ($password === '') {
            $password = Str::random(10);
        }

        return User::updateOrCreate(
            ['email' => $email],
            [
                'name' => $name,
                'role' => $role,
                'password' => Hash::make($password),
            ]
        );
    }

    public function rules(): array
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'email', 'max:255'],
            'role' => ['required', 'in:admin_elearning,guru,siswa'],
            'password' => ['nullable', 'string', 'min:6'],
        ];
    }

    public function customValidationMessages()
    {
        return [
            'name.required' => 'Kolom name wajib diisi.',
            'email.required' => 'Kolom email wajib diisi.',
            'email.email' => 'Format email tidak valid.',
            'role.required' => 'Kolom role wajib diisi.',
            'role.in' => 'Role harus salah satu dari: admin_elearning, guru, siswa.',
            'password.min' => 'Password minimal 6 karakter.',
        ];
    }
}
